pin/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetView, PasswordResetCompleteView,PasswordResetConfirmView
from django.urls import reverse_lazy
app_name = 'accounts'

urlpatterns = [

    url(r'^login/$', LoginView.as_view(template_name="accounts/login.html"), name="login"),
    url(r'^logout/$', LogoutView.as_view(template_name="accounts/logout.html"), name="logout"),
    url(r'^register/$', views.register, name="register"),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),

    url(r'^reset-password/$', PasswordResetView.as_view(template_name="accounts/reset_password.html",
                                                        success_url=reverse_lazy('accounts:password_reset_done'),
                                                        email_template_name="accounts/reset_password_email.html"),
        name='reset_password'),

    url(r'^reset-password/done/$', PasswordResetDoneView.as_view(template_name="accounts/reset_password_done.html"),
        name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(
                                                            template_name="accounts/reset_password_confirm.html",
                                                            success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),

    url(r'^reset-password/complete/$', PasswordResetCompleteView.as_view(template_name="accounts/reset_password_complete.html"), name='password_reset_complete')

]

pin/home/urls.py
from django.conf.urls import url
from home.views import HomeView, CreatePassword
from home import views
app_name = 'home'
urlpatterns = [
    #url(r'^$', views.home, name='home'), url(r'^$', views.home, name="home"),
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^password/$', views.passwords, name='modify_password'),
    url(r'^delete/(?P<password_id>[0-9]+)/$', views.password_delete, name='delete_view'),
    url(r'^password/create/$', CreatePassword.as_view(), name='create_password'),
]

pin/pin/urls.py
from django.contrib import admin
from django.urls import path, include
from pin import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('home/', include('home.urls', namespace='home')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pin/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.

class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset().filter(city='London')


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length = 100, default='')
    city = models.CharField(max_length = 100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField( upload_to='profile_image', blank=True)



    london = UserProfileManager()
    objects = models.Manager()

    def __str__(self):
        return self.user.username


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

pin/home/models.py
from django.db import models
from django.contrib.auth.models import User

# class Post(models.Model):
#     post = models.CharField(max_length=500)
#     user = models.ForeignKey(User, on_delete=models.CASCADE)

class Post(models.Model):
    website = models.CharField(max_length=500)
    name = models.CharField(max_length=500)
    pin = models.CharField(max_length=500)
    useridas =models.CharField(max_length=500)
    #user = models.ForeignKey(User, on_delete=models.CASCADE)

class Password(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='+')
    website = models.CharField(max_length=100, default='')
    name = models.CharField(max_length=100, default='')
    pin = models.CharField(max_length=100, default='')

    USERNAME_FIELD = 'website'

pin/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import UserProfile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):
    template_name='/something/else'

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )

pin/home/forms.py
from django import forms
from home.models import  Password, Post
from django.forms import ModelForm
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

class HomeForm(forms.ModelForm):
    post = forms.CharField()
    #widget=forms.TextInput(
#         attrs={
#             'class': 'form-control',
#             'placeholder': 'Write a post...'
#         }
#     ))

    class Meta:
        model = Post
        fields = ('post',)

class ModifyPassword(forms.ModelForm):

    class Meta:
        model = Password
        fields = (
            'website',
            'name',
            'pin',
        )

class CreatePinForm(forms.ModelForm):
    #template_name='/something/else'
    pin = forms.CharField()
    class Meta:
        model = Password
        fields = (
            'website',
            'name',
            'pin',
        )

class PasswordCreationForm(UserCreationForm):
   # website = forms.EmailField(required=True)

    class Meta:
        model = Password
        fields = (
            'website',
            'name',
            'pin',
        )

    def save(self, commit=True):
        new_password = super(PasswordCreationForm, self).save(commit=False)
        new_password.website = self.cleaned_data['website']
        new_password.name = self.cleaned_data['name']
        new_password.pin = self.cleaned_data['pin']

        if commit:
            new_password.save()

        return new_password

pin/accounts/views.py
# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import UserChangeForm
from accounts.forms import RegistrationForm,EditProfileForm
from django.contrib.auth.decorators import login_required



def home(request):
    numbers = [1,2,3,4,5]
    name = 'Max Goodridge'

    args = {'myName': name, 'numbers': numbers}
    return render(request, 'accounts/home.html', args)

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:home')
    else:
        form = RegistrationForm()

    args={'form': form}
    return render(request, 'accounts/reg_form.html', args)


def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

pin/home/views.py
# def home(request):
#     return HttpResponse('Its works!')

from django.views.generic import TemplateView, ListView
from django.shortcuts import render, redirect
#from django.contrib.auth.models import User

from home.forms import HomeForm, ModifyPassword,CreatePinForm, PasswordCreationForm
from home.models import Post, Password
from django.urls import reverse
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm

class HomeView(TemplateView):
    template_name = 'home/home.html'


    def get(self, request):
        form = HomeForm()
        passwords = Password.objects.all()
        args = {
            'form': form, 'passwords': passwords
        }
        return render(request, self.template_name, args)


    def post(self, request):
        form = HomeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            text = form.cleaned_data['post']
            form = HomeForm()
            return redirect('home:home')

        args = {'form': form, 'text': text}
        return render(request, self.template_name, args)

def passwords(request):
    if request.method == 'POST':
        form = ModifyPassword(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('home:home'))
    else:
        form = ModifyPassword(instance=request.user)
        args = {'form': form}
        return render(request, 'home/modify_passwords.html', args)


def password_delete(request, password_id=None):
        object = Password.objects.get(id=password_id)
        object.delete()
        return redirect(reverse('home:home'))
        #return render(request, 'ur template where you want to redirect')




class CreatePassword(TemplateView):

    template_name = 'home/create_new_password.html'

    def get(self, request):
        form = CreatePinForm()
        passwords = Password.objects.all()


        args = {
            'form': form, 'password': passwords
        }
        return render(request, self.template_name, args)

    def post(self, request):
        form = CreatePinForm(request.POST)
        if form.is_valid():
            password = form.save(commit=False)
            password.user = request.user
            password.save()

            text = form.cleaned_data['website']
            form = CreatePinForm()
            return redirect('home:home')

        args = {'form': form, 'text': text}
        return render(request, self.template_name, args)

        #form = PasswordCreationForm()

   # args = {'form': form}
    #return render(request, 'home/create_new_password.html', args)

pin/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

pin/accounts/templates/accounts/editProfile.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

pin/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

pin/accounts/templates/accounts/home.html
{% extends 'base.html' %}
<h1>Home</h1>
{% block head %}
<title>Home</title>
{% endblock %}

{% block body %}
<h1>Home</h1>
{% endblock %}

pin/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Welcome</h1>
    <p>
        You can login here
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</div>
{% endblock %}

pin/accounts/templates/accounts/logout.html
{% extends 'base.html' %}


{% block body %}
<div class="container">
    <h1>Logged out</h1>
    <p>
        You have logged out!
    </p>
</div>
{% endblock %}

pin/accounts/templates/accounts/profile.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Description: {{ user.userprofile.description }}</p>
    <p>Phone: {{ user.userprofile.phone }}</p>
    <p>City: {{ user.userprofile.city }}</p>
    <p>Website: {{ user.userprofile.website }}</p>
    {% if user.userprofile.image %}
    <img src="{{ user.userprofile.image.url }}" width="240">
    {% endif %}
</div>

{% endblock %}

pin/accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>

</div>
{% endblock %}

pin/accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset</h1>
    <p>
        Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

pin/accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset complete</h1>
    <a href="{% url 'accounts:login' %}">Log in</a>
</div>
{% endblock %}

pin/accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Enter new password</h1>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

pin/accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset sent</h1>
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

        If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>
</div>
{% endblock %}

pin/accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}