pin/home/urls.py
from django.conf.urls import url
from home.views import HomeView, CreatePassword
from home import views
app_name = 'home'
urlpatterns = [
    #url(r'^$', views.home, name='home'), url(r'^$', views.home, name="home"),
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^password/$', views.passwords, name='modify_password'),
    url(r'^delete/(?P<password_id>[0-9]+)/$', views.password_delete, name='delete_view'),
    url(r'^password/create/$', CreatePassword.as_view(), name='create_password'),
]

pin/pin/urls.py
from django.contrib import admin
from django.urls import path, include
from pin import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('home/', include('home.urls', namespace='home')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pin/home/models.py
from django.db import models
from django.contrib.auth.models import User

# class Post(models.Model):
#     post = models.CharField(max_length=500)
#     user = models.ForeignKey(User, on_delete=models.CASCADE)

class Post(models.Model):
    website = models.CharField(max_length=500)
    name = models.CharField(max_length=500)
    pin = models.CharField(max_length=500)
    useridas =models.CharField(max_length=500)
    #user = models.ForeignKey(User, on_delete=models.CASCADE)

class Password(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='+')
    website = models.CharField(max_length=100, default='')
    name = models.CharField(max_length=100, default='')
    pin = models.CharField(max_length=100, default='')

    USERNAME_FIELD = 'website'

pin/home/forms.py
from django import forms
from home.models import  Password, Post
from django.forms import ModelForm
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

class HomeForm(forms.ModelForm):
    post = forms.CharField()
    #widget=forms.TextInput(
#         attrs={
#             'class': 'form-control',
#             'placeholder': 'Write a post...'
#         }
#     ))

    class Meta:
        model = Post
        fields = ('post',)

class ModifyPassword(forms.ModelForm):

    class Meta:
        model = Password
        fields = (
            'website',
            'name',
            'pin',
        )

class CreatePinForm(forms.ModelForm):
    #template_name='/something/else'
    pin = forms.CharField()
    class Meta:
        model = Password
        fields = (
            'website',
            'name',
            'pin',
        )

class PasswordCreationForm(UserCreationForm):
   # website = forms.EmailField(required=True)

    class Meta:
        model = Password
        fields = (
            'website',
            'name',
            'pin',
        )

    def save(self, commit=True):
        new_password = super(PasswordCreationForm, self).save(commit=False)
        new_password.website = self.cleaned_data['website']
        new_password.name = self.cleaned_data['name']
        new_password.pin = self.cleaned_data['pin']

        if commit:
            new_password.save()

        return new_password

pin/home/views.py
# def home(request):
#     return HttpResponse('Its works!')

from django.views.generic import TemplateView, ListView
from django.shortcuts import render, redirect
#from django.contrib.auth.models import User

from home.forms import HomeForm, ModifyPassword,CreatePinForm, PasswordCreationForm
from home.models import Post, Password
from django.urls import reverse
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm

class HomeView(TemplateView):
    template_name = 'home/home.html'


    def get(self, request):
        form = HomeForm()
        passwords = Password.objects.all()
        args = {
            'form': form, 'passwords': passwords
        }
        return render(request, self.template_name, args)


    def post(self, request):
        form = HomeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            text = form.cleaned_data['post']
            form = HomeForm()
            return redirect('home:home')

        args = {'form': form, 'text': text}
        return render(request, self.template_name, args)

def passwords(request):
    if request.method == 'POST':
        form = ModifyPassword(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('home:home'))
    else:
        form = ModifyPassword(instance=request.user)
        args = {'form': form}
        return render(request, 'home/modify_passwords.html', args)


def password_delete(request, password_id=None):
        object = Password.objects.get(id=password_id)
        object.delete()
        return redirect(reverse('home:home'))
        #return render(request, 'ur template where you want to redirect')




class CreatePassword(TemplateView):

    template_name = 'home/create_new_password.html'

    def get(self, request):
        form = CreatePinForm()
        passwords = Password.objects.all()


        args = {
            'form': form, 'password': passwords
        }
        return render(request, self.template_name, args)

    def post(self, request):
        form = CreatePinForm(request.POST)
        if form.is_valid():
            password = form.save(commit=False)
            password.user = request.user
            password.save()

            text = form.cleaned_data['website']
            form = CreatePinForm()
            return redirect('home:home')

        args = {'form': form, 'text': text}
        return render(request, self.template_name, args)

        #form = PasswordCreationForm()

   # args = {'form': form}
    #return render(request, 'home/create_new_password.html', args)

pin/home/templates/home/create_new_password.html
{% extends 'base.html' %}


{% block head %}
<title>Password</title>
{% endblock %}

{% block body %}
<div class="container">
 <form  method="post">
 {% csrf_token %}


        {{ form.as_p }}
          <input type="checkbox" name="vehicle1" value="True"> Upper case<br>
          <input type="checkbox" name="vehicle2" value="True"> With numbers<br>
          <input type="checkbox" name="vehicle3" value="True" checked> With simbols<br>
          <input type="checkbox" name="vehicle3" value="True" checked> With word<br>
          <input type="checkbox" name="vehicle3" value="True" checked> Length <input type="text" name="Length" ><br>

        <div>

</div>
        <button type="submit">Generate pin</button>
        <button type="submit">Submit</button>
        <button type="submit"><a href="{% url 'home:home' %}">Cancel</a></button>
    </form>
</div>

{% endblock %}

pin/home/templates/home/home.html
{% extends 'base.html' %}

{% block body %}

    <div class="container">
        <div class="col-md-8">

            <h1>Your PASSWORD list</h1>
            <p>All your password are here.</p>

        <div class="col-md-10 col-md-offset-1">

            <div class="panel panel-default panel-table">
              <div class="panel-heading">
                <div class="row">
                  <div class="col col-xs-6">
                    <h3 class="panel-title">Passwords</h3>
                  </div>
                  <div class="col col-xs-6 text-right">
                    <button type="button"><a href="{% url 'home:create_password' %}">Create New</button>
                  </div>
                </div>
              </div>
              <div >
                <table class="table table-striped table-bordered table-list">
                  <thead>
                    <tr>
                        <th >Website</th>
                        <th >User name</th>
                        <th >Password</th>
                    </tr>
                  </thead>
                  <tbody>
                         {% for password in passwords %}
                            {% if password.user_id == user.id %}
                              <tr>
                                <!--<td align="center">
                                 <button type="button" ><a href="{% url 'home:modify_password' %}">Modify</button>
                                 <button type="button" ><a href="">Delete</button>
                                </td>
                                -->
                                <td>{{ password.website }}</td>
                                <td>{{ password.name }}</td>
                                <td>{{ password.pin }} </td>
                              </tr>
                            </tbody>
                        {% endif %}
                        {% endfor %}
                </table>

              </div>
            </div>
        </div>
       </div>
      </div>
{% endblock %}

pin/home/templates/home/modify_passwords.html
{% extends 'base.html' %}


{% block head %}
<title>Password</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}