pin/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetView, PasswordResetCompleteView,PasswordResetConfirmView
from django.urls import reverse_lazy
app_name = 'accounts'

urlpatterns = [

    url(r'^login/$', LoginView.as_view(template_name="accounts/login.html"), name="login"),
    url(r'^logout/$', LogoutView.as_view(template_name="accounts/logout.html"), name="logout"),
    url(r'^register/$', views.register, name="register"),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),

    url(r'^reset-password/$', PasswordResetView.as_view(template_name="accounts/reset_password.html",
                                                        success_url=reverse_lazy('accounts:password_reset_done'),
                                                        email_template_name="accounts/reset_password_email.html"),
        name='reset_password'),

    url(r'^reset-password/done/$', PasswordResetDoneView.as_view(template_name="accounts/reset_password_done.html"),
        name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(
                                                            template_name="accounts/reset_password_confirm.html",
                                                            success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),

    url(r'^reset-password/complete/$', PasswordResetCompleteView.as_view(template_name="accounts/reset_password_complete.html"), name='password_reset_complete')

]

pin/home/urls.py
from django.conf.urls import url
from home.views import HomeView, CreatePassword
from home import views
app_name = 'home'
urlpatterns = [
    #url(r'^$', views.home, name='home'), url(r'^$', views.home, name="home"),
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^password/$', views.passwords, name='modify_password'),
    url(r'^delete/(?P<password_id>[0-9]+)/$', views.password_delete, name='delete_view'),
    url(r'^password/create/$', CreatePassword.as_view(), name='create_password'),
]

pin/pin/urls.py
from django.contrib import admin
from django.urls import path, include
from pin import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('home/', include('home.urls', namespace='home')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pin/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.

class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset().filter(city='London')


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length = 100, default='')
    city = models.CharField(max_length = 100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField( upload_to='profile_image', blank=True)



    london = UserProfileManager()
    objects = models.Manager()

    def __str__(self):
        return self.user.username


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

pin/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import UserProfile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):
    template_name='/something/else'

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )

pin/accounts/views.py
# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import UserChangeForm
from accounts.forms import RegistrationForm,EditProfileForm
from django.contrib.auth.decorators import login_required



def home(request):
    numbers = [1,2,3,4,5]
    name = 'Max Goodridge'

    args = {'myName': name, 'numbers': numbers}
    return render(request, 'accounts/home.html', args)

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:home')
    else:
        form = RegistrationForm()

    args={'form': form}
    return render(request, 'accounts/reg_form.html', args)


def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

pin/accounts/templates/base.html
<html>
   <head>
        <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
       {% block head %}
        <title></title>
        {% endblock %}
    </head>
   <body>
       <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
          <a class="navbar-brand" href="/">Pin generator</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active"><a class="nav-link" href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a> </li>
              <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:view_profile' %}">Profile <span class="sr-only">(current)</span></a> </li>
              <li class="nav-item active"> <a class="nav-link" href="{% url 'accounts:edit_profile' %}">Edit profile <span class="sr-only">(current)</span></a></li>
             </ul>
            <ul class="nav navbar-nav ml-auto">
               <li class="nav-item active"> <a class="nav-link" href="{% url 'accounts:logout' %}">Log out <span class="sr-only">(current)</span></a></li>
               <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:change_password' %}">Change password <span class="sr-only">(current)</span></a></li>
               <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:reset_password' %}">Reset password <span class="sr-only">(current)</span></a></li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav ml-auto">
              <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:register' %}">Register <span class="sr-only">(current)</span></a></li>
              <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:login' %}">Login <span class="sr-only">(current)</span></a></li>
            </ul>
            {% endif %}
          </div>
        </nav>
        {% block body %}
        <h1>Base</h1>
        {% endblock %}
    </body>
</html>